name: trello

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trello_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - trello_network

  nginx:
    image: nginx:alpine
    container_name: trello_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - trello_network

networks:
  trello_network:
    driver: bridge